# Generated by Django 2.2.1 on 2019-05-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneform',
            old_name='population',
            new_name='messages',
        ),
    ]
