# Generated by Django 2.2.1 on 2019-05-24 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0002_auto_20190524_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
